### ISSUE TITLE
Editor dosent resize with screen

### ISSUE THREAD

**Issue by Haxified** [egoist/vue-monaco#10]
When I set the width, it will stay with that width whenever I resize the window... please help.

**Comment by Haxified1** [comment]
Is this project dead

yes

ok

**Comment by zantiu** [comment]
You can activate the resize by yourself with editor.layout after the container has resized.
https://github.com/Microsoft/monaco-editor/issues/543

**Comment by rockymontana** [comment]
Seems like its pretty much dead, yes. Unfortunately

**Comment by egoist** [comment]
@Haxified @rockymontana [the comment above](https://github.com/egoist/vue-monaco/issues/10#issuecomment-402343053) literally answered the issue. If you want something more just ask for it or open a pull request, commenting like that helps nobody.

**Comment by rockymontana** [comment]
You are absolutely right. 
Sorry about that. I will remove my comment.

**Comment by Haxified** [comment]
Tiny bit late to the issue hahaha @egoist
