### ISSUE TITLE
Can't paste in editor

### ISSUE THREAD

**Issue by khanhnd69** [egoist/vue-monaco#13]

**Comment by khanhnd69** [comment]
I sloved this problem:
Go to monaco-editor
node_modules/monaco-editor/esm/vs/base/common/platform.js
change 
`if (typeof process === 'object' && typeof process.nextTick === 'function' && typeof process.platform === 'string') {`
To
`if (typeof process === 'object' && typeof process.nextTick === 'function' && typeof process.platform === 'string' && process.platform !== "browser") {`

**Comment by khanhnd69** [comment]
Or in vue.config.js
module.exports = {
...,
  configureWebpack:{
    node: {
      process: false,
    }
  }
}

**Comment by ramiy** [comment]
I confirm, the above example helped. Now I can't copy & paste inside the editor.

This is my **vue.config.js** file:

```
const MonocoEditorPlugin = require('monaco-editor-webpack-plugin')

module.exports = {
  configureWebpack: {
    node: {
      process: false,
    },
    plugins: [
      new MonocoEditorPlugin()
    ]
  }
}
```

Thank you @khanhnd69 !
