### ISSUE TITLE
Weird "border/underline" 

### ISSUE THREAD

**Issue by AllanOricil** [egoist/vue-monaco#161]
How can I remove this weird line?

![image](https://user-images.githubusercontent.com/55927613/108630912-40a1e900-745f-11eb-8497-e80241525802.png)

**Comment by AllanOricil** [comment]
This is caused by the auto suggestion box. I just deactivated it with css. 

````css
.monaco.suggest-widget{
    display:none;
}

**Comment by mibzman** [comment]
Setting `display: none` didn't work for me, but this does:
```
.suggest-widget {
  border-style: none;
}

```
