### ISSUE TITLE
TypeError: Cannot set property 'apex' of undefined

### ISSUE THREAD

**Issue by Wjinlei** [egoist/vue-monaco#167]
TypeError: Cannot set property 'apex' of undefined

**Comment by kubido** [comment]
you need to set up the `MonacoWebpackPlugin`, I put mine in `vue.config.js`

```js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
  configureWebpack: {
    plugins: [
      new MonacoWebpackPlugin({
        languages: ['javascript']
      })
    ]
  }
}

```

**Comment by Wjinlei** [comment]
Thank you，but this doesn't work for me

Here i am
```js
languages: ['javascript', 'css', 'html', 'typescript']
```
 But again "Cannot set property 'css' of undefined”

**Comment by linyanbin666** [comment]
@Wjinlei How do you solve "Cannot set property 'css' of undefined” ?

**Comment by Wjinlei** [comment]
> @Wjinlei How do you solve "Cannot set property 'css' of undefined” ?

我并没有解决这个问题，我换codemirror了
