### ISSUE TITLE
An unexpected style appears in the editor

### ISSUE THREAD

**Issue by januwA** [egoist/vue-monaco#197]
![image](https://user-images.githubusercontent.com/22570563/133406165-f773c8ed-8f2b-4815-9d9d-67da81657b9f.png)

I found out that he was caused by this
![image](https://user-images.githubusercontent.com/22570563/133406221-24ba32f7-5e0a-4c9e-8728-f2cac5a3d5b2.png)

packages
```
 "dependencies": {
    "vue": "2.6.14",
    "monaco-editor": "^0.26.0",
    "vue-monaco": "^1.2.2",
},
  "devDependencies": {
    "monaco-editor-webpack-plugin": "^4.1.2",
}
```

vue.config.js
```js
const MonacoEditorPlugin = require("monaco-editor-webpack-plugin");
   
 config.plugin("MonacoEditorPlugin").use(MonacoEditorPlugin, [
      {
        languages: ["json"],
      },
    ]);
```

component
```vue
<template>
  <div class="components-container">
    <div class="w-100 border" style="height: 600px">
      <MonacoEditor
        class="w-100 h-100"
        v-model="jsonData"
        language="json"
        :options="options"
      />
    </div>
  </div>
</template>

<script>
import MonacoEditor from "vue-monaco";

export default {
  components: { MonacoEditor },
  data() {
    return {
      options: {
        theme: "vs-dark",
      },
      jsonData: JSON.stringify({ name: "ajanwu" }, null, "  "),
    };
  },
};
</script>
```

Can you help me look at this problem? thanks

**Comment by gorillapower** [comment]
I am having the same issue, did you find a solution yet?

**Comment by gorillapower** [comment]
@januwA see this answer here https://github.com/egoist/vue-monaco/issues/161 for a resolution

**Comment by januwA** [comment]
> @januwA see this answer here #161 for a resolution

Thank you, I deleted `.suggest-widget` using js, but the way to use css is better

**Comment by januwA** [comment]
I don’t know what caused this BUG. I used it in [Angular](https://januwa.github.io/nestjs-tools/dto) and in the [browser](https://januwa.github.io/web-code-editor/monaco.html), but it didn’t appear.
