### ISSUE TITLE
Uncaught Error: Unexpected usage

### ISSUE THREAD

**Issue by soneway** [egoist/vue-monaco#22]
errors.js?0f90:57 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?8c76:468)
    at eval (webWorker.js?a9b4:39)
    at eval (errors.js?0f90:57)

**Comment by eljefedelrodeodeljefe** [comment]
I vendored this plugin and imported `const monaco = require('monaco-editor/esm/vs/editor/editor.api')` at top. Works fine then, afaict.

**Comment by Symbolk** [comment]
> I vendored this plugin and imported `const monaco = require('monaco-editor/esm/vs/editor/editor.api')` at top. Works fine then, afaict.

Could you provide more details about this solution? Like how to import and register the component, thanks!

**Comment by Symbolk** [comment]
My solution: Configure webpack-plugin in vue.config.js, instead of webpack.config.js:
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')

module.exports = {
  configureWebpack: {
   plugins: [
      new MonacoWebpackPlugin({
        // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
        languages: ['javascript', 'css', 'html', 'typescript', 'json']
      })
    ]
  }
```

**Comment by egoist** [comment]
Try the latest version and follow the [README](https://github.com/egoist/vue-monaco#use-esm-version-with-webpack), let me know if it still doesn't work for you.

**Comment by Symbolk** [comment]
> Try the latest version and follow the [README](https://github.com/egoist/vue-monaco#use-esm-version-with-webpack), let me know if it still doesn't work for you.

The highlighting works as expected, though there is still error message reported in the console. 

Please see my test project, in which I also used another lib called monaco-editor-vue.

https://github.com/Symbolk/vue-monaco-test

**Comment by wxk6b1203** [comment]
My workaround:
1. use `monaco-editor-webpack-plugin`
  ```javascript
  const MonacoEditorPlugin = require('monaco-editor-webpack-plugin')  

  module.exports = {
    // 选项...
    configureWebpack: {
      node: {
        process: true,
      },
      plugins: [
        new MonacoEditorPlugin({
          features: ['!gotoSymbol']
        })
      ]
    },
    runtimeCompiler: true
  }
  ```

2. setup `package.json` from the project root, manually set dependency to 1.7.0:
```diff
- "monaco-editor-webpack-plugin": "^1.8.2",
+ "monaco-editor-webpack-plugin": "1.7.0",
```

I know it is not a good way. Anyway, it solved the problem...

**Comment by WhatFreshHellIsThis** [comment]
This is still a problem a year later following the directions on the readme to install and usage.  Same exact error message about "unexpected usage".  I will try the workarounds here but it appears the instructions are incorrect still or there is some other problem.  Not sure why this issue was closed.
