### ISSUE TITLE
how to create DiffEditor?

### ISSUE THREAD

**Issue by pinalbhatt** [egoist/vue-monaco#25]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-monaco/issues/25)

Is it possible to create DiffEditor using this package? If yes can anybody provide pointers to that? thanks in advance.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-monaco/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Symbolk** [comment]
Same request, currently I am using this wrapper: https://github.com/FE-Mars/monaco-editor-vue

**Comment by egoist** [comment]
See https://github.com/egoist/vue-monaco#use-the-diffeditor

**Comment by Symbolk** [comment]
Wow, jumping version~

**Comment by egoist** [comment]
Yeah, because it introduced a small [breaking change](https://github.com/egoist/vue-monaco/releases/tag/v1.0.0).
