### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'editor' of undefined"

### ISSUE THREAD

**Issue by cookieY** [egoist/vue-monaco#5]
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'editor' of undefined"

按照文档的描述引入 报错

**Comment by egoist** [comment]
are you sure `window.monaco` is available in your page? please provide a minimal repo too

**Comment by cookieY** [comment]
我不太理解第一个步骤 You need to include monaco-editor first.  这个monaco-editor 是引入到哪里？

**Comment by egoist** [comment]
add to your html
