### ISSUE TITLE
Scroll does not work well in Firefox

### ISSUE THREAD

**Issue by frsechet** [egoist/vue-monaco#59]
Already solved by https://github.com/egoist/vue-monaco/pull/54, only need a new release to npm!

See comment https://github.com/egoist/vue-monaco/pull/54#issuecomment-530613366

**Comment by iquidus** [comment]
In the meantime I have an updated fork published here: https://www.npmjs.com/package/vue-monaco-d0x

**Comment by frsechet** [comment]
Fixed in 1.2!
